### ISSUE TITLE
Denying permission isn't respected 

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/chat-config#30]
**Looking forward for reporting a security issue:**

I don't think there is one

**Describe the bug**

In mobile. Try to share img in chat but deny access, this will lead to your file manager to open

**To Reproduce**

1. Go to chat with you mobile device 
2. Click on screen icon
3. Deny
4. Click appropriate IMG
5. See the IMG in chat

**Expected behavior**

 Not to open.

**Video**

https://user-images.githubusercontent.com/88248797/169374029-190bfe35-b135-4bd2-b81b-91c68c5a1de2.mp4

**Desktop (please complete the following information):**

 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**

 - Device: [oppo a55]
 - OS: [android version 11]
 - Browser: [brave]
 - Version: [1.38.113]
 - update Date: [10/may]
 - Chromium version:  [Chromium 101]

**Additional context**

We all agree, that the true solution is allow access everytime option🤣

**Comment by raisedadead** [comment]
This issue is unrelated to us in many folds. 

The application requesting (and not respecting permission boundaries is Brave), and the second part is any core functionality issues (like uploading images) with [Rocket.Chat](https://rocket.chat) needs to be reported to them.

**Comment by Sboonny** [comment]
Oh I didn't know that, I will report it to them. Thanks for your time
